nav:
  - 首页: index.md
  - 架构: architecture.md
  - 用户指南:
      - 环境准备: user_guide/environment_preparation.md
      - 快速开始: user_guide/quick_start.md
      - 部署模式指南: user_guide/deploy_mode_guide.md
      - 服务部署:
          - PD 分离部署: user_guide/service_deployment/pd_disaggregation_deployment.md
          - PD 混部部署: user_guide/service_deployment/pd_hybrid_deployment.md
          - 配置参考: user_guide/service_deployment/config_reference.md
          - 更新配置白名单: user_guide/service_deployment/update_config_whitelist.md
      - Standby 部署: user_guide/standby_deployment.md
      - 链路追踪部署: user_guide/tracing_deployment.md
      - KV Pool 部署: user_guide/KV_pool_deployment_guide.md
      - KV Cache 亲和部署: user_guide/KV_cache_affinity_deployment.md
      - 会话亲和调度部署: user_guide/session_affinity_deployment.md
      - 手动扩缩容指南: user_guide/manual_scaling_guide.md
      - 组件:
          - Controller: user_guide/components/controller.md
          - Coordinator: user_guide/components/coordinator.md
          - Engine Server: user_guide/components/engine_server.md
          - Node Manager: user_guide/components/node_manager.md
      - 面向服务接口:
          - 说明: user_guide/service_oriented_interface/description.md
      - 面向服务优化工具: user_guide/service_oriented_optimization_tool.md
      - 日志配置: user_guide/log_config_guide.md
      - 从 vLLM Ascend 制作镜像: user_guide/make_image_from_vllm_ascend.md
      - 常见问题与解决: user_guide/solutions_to_common_problems.md
  - 特性:
      - PD 分离: features/PD_disaggregation.md
  - 开发者指南:
      - Docker 单机: developer_guide/docker_only/single_container_docker_only.md
      - Docker 多机: developer_guide/docker_only/multi_container_docker_only.md
      - CRD 部署设计: developer_guide/crd_deployment/crd_deployment_design.md
      - 实例级手动扩缩容设计: developer_guide/instance_manual_scaling/manual_scaling_design.md
      - 故障管理设计: developer_guide/fault_tolerance/fault_manager_design.md
      - EndPoint 断链取消设计: developer_guide/engine_disconnect_cancellation_design.md
      - Metrics 可观测性设计: developer_guide/metrics/metrics_design.md
      - 本地构建文档: developer_guide/build_docs/build_docs.md
  - API 参考:
      - 接口说明: api_reference/interface_description.md
      - 服务接口: api_reference/service_interface.md
      - 管理与监控接口: api_reference/management_and_monitoring_interfaces.md
